server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: test
    password: 0000
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: \
            client-secret: \
            scope: profile, email
            
          kakao:
            authorization-grant-type: authorization_code
            client-id: \
            client-secret: \
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao
            
          naver:
            client-id: \
            client-secret: \
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:  
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  
            
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail :
    host : smtp.gmail.com
    port : 587
    username : \
    password : \
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true 
    
mybatis:
 mapper-locations: classpath:mappers/*.xml
 configuration: 
   mapUnderscoreToCamelCase: true
   
imp_key: \
imp_secret: \





  

   
   
   
